-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 13:24:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`user` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(128) NOT NULL,
  `telephone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `linkedin` VARCHAR(128) NOT NULL,
  `github` VARCHAR(128) NOT NULL,
  `twitter` VARCHAR(128) NOT NULL,
  `cv` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`skills` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(128) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skills_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_skills_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfolio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`competences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`competences` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`competences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_competences_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_competences_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfolio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`realisations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`realisations` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`realisations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `subtitle` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `description` VARCHAR(128) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_realisations_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_realisations_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `portfolio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `portfolio`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `portfolio`;
INSERT INTO `portfolio`.`user` (`id`, `firstname`, `lastname`, `title`, `description`, `telephone`, `email`, `linkedin`, `github`, `twitter`, `cv`, `photo`) VALUES (1, 'Farah', 'SELTANY', 'Développeur Web', 'Phrase d\'accroche que je n\'ai pas encore trouvée', 0625457371, 'farahseltany@gmail.com', 'https://www.linkedin.com/in/farahseltanyn/', 'https://github.com/farah-seltany', 'https://twitter.com/SeltanyN', 'CV', 'photo');

COMMIT;

